///////////////////////////////////////////////////////////////////////////////
// File generated by HDevelop for HALCON/C++ Version 23.05.0.0
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// Ensure that the interface encoding is set to locale encoding by calling
// SetHcppInterfaceStringEncodingIsUtf8(false) at the beginning of the program.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
///////////////////////////////////////////////////////////////////////////////

#include "HalconCpp.h"
#include "HDevThread.h"



using namespace HalconCpp;


// Chapter: Tools / Geometry
// Short Description: Sort tuple pairs. 
void sort_pairs (HTuple hv_T1, HTuple hv_T2, HTuple hv_SortMode, HTuple *hv_Sorted1, 
    HTuple *hv_Sorted2)
{

  // Local iconic variables

  // Local control variables
  HTuple  hv_Indices1, hv_Indices2;

  //Sort tuple pairs.
  //
  //input parameters:
  //T1: first tuple
  //T2: second tuple
  //SortMode: if set to '1', sort by the first tuple,
  //   if set to '2', sort by the second tuple
  //
  if (0 != (HTuple(int(hv_SortMode==HTuple("1"))).TupleOr(int(hv_SortMode==1))))
  {
    TupleSortIndex(hv_T1, &hv_Indices1);
    (*hv_Sorted1) = hv_T1.TupleSelect(hv_Indices1);
    (*hv_Sorted2) = hv_T2.TupleSelect(hv_Indices1);
  }
  else if (0 != (HTuple(HTuple(int(hv_SortMode==HTuple("column"))).TupleOr(int(hv_SortMode==HTuple("2")))).TupleOr(int(hv_SortMode==2))))
  {
    TupleSortIndex(hv_T2, &hv_Indices2);
    (*hv_Sorted1) = hv_T1.TupleSelect(hv_Indices2);
    (*hv_Sorted2) = hv_T2.TupleSelect(hv_Indices2);
  }
  return;
}
